### PR TITLE
Java8mig-724

### PR DESCRIPTION
**Pull request by apgsga-uge**
delivery of sudoers right from rpm package

### CODE REVIEW

**Comment by apgsga-uge** [comment]
> Approved, only echoing for now right?

Well, yes and no... just echoing, but to specific file in final deployment directory - so it‘s actually activating the rights.

**Comment by apgsga-jhe** [comment]
> > Approved, only echoing for now right?
> 
> Well, yes and no... just echoing, but to specific file in final deployment directory - so it‘s actually activating the rights.

Ups ... yep, I should have better look ;) ... bin any case approved :)

**Comment by apgsga-uge** [comment]
moved options to variable as suggested by @chhex

**Comment by apgsga-uge** [comment]
push yum command repo restrictions

**Pull request merged**
